### ISSUE TITLE
Update packages to latest

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#115]
This is actually realted to `firebase` and `firebase-tools` at the top level (client facing) app, Everything else is up to date, but updating one of those two causes 401/404 whe calling cloud functinos. We need to:

- investigate which of these packages is causing problems
- how and why the problem arises
- upon solving update everything to @latest version

**Comment by silviot** [comment]
This rings a bell to me: I believe the current code has a workaround for a bug that is no longer present in firebase. I believe removing the workaround would make cloud functions work with newer firebase tools.

**Comment by silviot** [comment]
[I believe this is the code that should be removed to make it work with newer `firebase`](https://github.com/eisbuk/EisBuk/blob/00b58cee38293420683a2ce90d3aa5c54e1bc1de/eisbuk-admin/src/config/envInfo.ts#L14-L19).

I remember the emulator would ignore the configured functions zone, always placing them in `us-central`. Maybe it's now fixed and the code linked above could be changed to always read `functionsZone = "europe-west6"`.
