### ISSUE TITLE
Reinstate Chromatic checks

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#130]
There was a Chromatic check as part of GitHub workflows which didn't allow for commits with unconfirmed chromatic changes to pass checks (and be merged/deployed). The latest known version is PR #95 . We should make (strict) chromatic checks part of the CI/CD process again.

**Comment by silviot** [comment]
I just reinstalled the chromatic Github app. It was installed under the project old URL (`silviot`) but not here:

![Screenshot from 2021-08-17 16-42-44](https://user-images.githubusercontent.com/396425/129747444-e3caf17a-5ec5-4423-a058-fa14a3e741df.png)

**Comment by silviot** [comment]
I removed the old project on chromatic and recreated it at the new location. We lost history. Not a big deal. Now checks work again.
