### ISSUE TITLE
Check "Intermediate state" necessity

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#196]
At certain points we've used local state to serve as "intermediate state" for the UI, while server confirms update... @silviot has brought to my attention the fact that this might not be necessary in each of the places we've used it (and maybe even anywhere) as firebase short-circuts the updates  locally (probably through `react-redux-firestore`). This needs to be investigated and checked for each location if it's at all necessary.

**Comment by silviot** [comment]
Sometimes the UI is driven by aggregate secondary data. In those cases when primary data is updated firebase only short circuits the primary records, but for the UI to update the following needs to happen:

* the request that does the changes needs to make it to the server (this might not happen on temporary disconnection or offline working)
* the trigger needs to be fired, and it needs to update the secondary data
* the secondary is pulled in by the client as soon as it changes

At best this requires some hundreds of milliseconds. The intermediate state lets the user know, during this time, that the update is not fully effective yet.

In short, the temporary state is necessary when the UI needs the secondary data to be up to date.

The magic is done by the `firestore` client in the `firebase` package. From [their docs](https://firebase.google.com/docs/firestore/query-data/listen):
> The initial state can come from the server directly, or from a local cache. If there is state available in a local cache, the query snapshot will be initially populated with the cached data, then updated with the server's data when the client has caught up with the server's state.

The above is not exactly relevant, but almost. I could not find where exactly I read that, when writing data, the local cache is updated first, and any listener that should receive those updates will receive them before they make it to the server.

**Comment by ikusteu** [comment]
Right...I see, it's sort of like a difference between:
```typescript
await someFirestoreUpdate
expect(updateResult).toBe(something)
```
and 
```typescript
await someFirestoreUpdate
await waitForCondition(someUpdateDataTriggerToTakeEffect)
```

**Comment by ikusteu** [comment]
I just got confused with the part of the old code updating the UI (disabling the attendance button) while the direct update takes effect (`markAbsence` updates the slot entry, and the `absentees` on the slot are read directly from the slot entry in `redux.firestore`)...right, it was read from `slotsByDay` (which need to be aggregated), not the `slots` (updated directly).

Anyhow, this issue should stay open and server as a reminder to remove unnecessary local store "intermediate states" (as the most of the updates are direct.
