### ISSUE TITLE
CI deployment to production is currently broken

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#231]
At some point the automatic CI deployment to production broke. Currently the deployed version has everything set to development: it tries to connect to localhost for firestore/auth.

I fixed the current production deployment manually, but this needs to be fixed in the repo.

**Comment by ikusteu** [comment]
I think I've messed something up with the constants and `__idDev__`

**Comment by ikusteu** [comment]
Checking now

**Comment by silviot** [comment]
This is now fixes. We've deployed multiple time successfully already.
