### ISSUE TITLE
Make sure the current date does not change when switching views

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#290]
Steps to reproduce:

* Navigate to a Wednesday on the `/` route. We call this `DateW`
* Click "Slots". The begin date will be two days earlier than `DateW`
* Click "Attendance". The date is now two days earlier than `DateW`

Views should never change the current date, unless the user clicks on the arrows.
If the current date is a Wednesday, and you go to a by-week view (like slots) and press "forward", the current date should still be Wednesday when you return to a by-day view. I.e. clicking a "forward one week" button should add 7 days to the current date, not jump to the next Monday.

**Comment by ikusteu** [comment]
I believe we had that one already...
