### ISSUE TITLE
Limit time when athletes can manage their bookings

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#326]
This story needs to be divided into substories. Here is an overall view of the desired functionality.

Background
-----

Instructors need to know how many people will come next month. They need to know four days before the beginning of the month.
Athletes might forget/be newly subscribed/have reasons to be an exception to the above rule.

Limits
---

We should never let athletes change their booking for the current month.
We should not let athletes manage bookings for next month if it starts in less than four days. Let's call this the `First Deadline`
We should display this in the UI for booking, letting athletes know what deadline they have. Something like "You can still manage your bookings for 2 days and 4 hours (January 27th)".
When two days are left we should send a reminder email to all athletes who have no booking in the next month, prompting them to book their lessons if they so wish.

Exceptions
---

Admins should be able to let individual athletes book their slots beyond the `First Deadline` up to a `Second Deadline` (five days into the month, up to midnight of the 5th).
When these athletes access the booking area a prominent message should ask them to complete their bookings as soon as possible, inform them of the `Second Deadline` and offer a button to "freeze" their bookings when they're done. This button will remove their "exceptional state" and they'll revert back to not being able to edit their bookings for the current month.

**Comment by ikusteu** [comment]
Closing this due to all of the (aforementioned) sub-tickets being open
