### ISSUE TITLE
Remove old migrations and make sure https cloud functions require admin status

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#389]
We have a bunch of migrations that, once run, are not needed anymore.
We should remove the buttons from the `/debug` page, and possibly remove their code. Or, since the code can provide useful hints when working on a new migration, we could move them to a different file that is not imported, and hence will not be deployed.

Let's also add `checkUser` to `unifyOffIceLabels` [that is currently missing it](https://github.com/eisbuk/EisBuk/blob/master/eisbuk-admin/functions/src/migrations.ts#L428).

**Comment by ikusteu** [comment]
Right...ok
Would `archve` folder make sense?
