### ISSUE TITLE
Default international prefix for phone numbers

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#429]
Phone numbers can be entered on the login form or on the create/edit athlete form.
Currently the international prefix is always required.
We should hava a configurable setting in the organization settings to provide a default international prefix. It could use a list of predefined prefixes, so that the user will enter the country name and the corresponding prefix will be saved.
When phone numbers are ~entered~ submitted without a prefix, the configured default prefix should be prepended to them.

**Comment by ikusteu** [comment]
Done. I remember doing it, and probably will for the rest of my life.
