### ISSUE TITLE
Feature: Athlete Revamp/ Customer Navigation 

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#488]
Covers Figma component mocks:
- NavBar / SubNav

## Discussion:
1. Is it worth creating a global IconButton that will be used here and (potentially) in AppBarAdmin when it receives a revamp?

## Tasks (Tickets):
1. Update existing `CustomerNavigation.tsx` to use new mock styles
2. Update existing `LinkTab` (as `IconButton` above?) within this file to use new mock styles.
3. Remove distinct Book Ice and Book Off Ice routes (am I wrong in understanding that they will both be included in same "Book" mock? Assume this will require additional updates to Slot rendering for combined route
4. Add a global `TopBar` component to render new Logo and `EisbukAvatar`
  a. Update `EisbukAvatar` to blend with tailwind colour palette

**Comment by ikusteu** [comment]
> Update existing LinkTab (as IconButton above?) within this file to use new mock styles.

I wouldn't call that `IconButton` not to get confused with MUI's IconButton which is literally an icon (no text) I like the `TabItem` as it's named in the spec, especially since it's a special kind of button (changes to semi-squared shape in mobile)

**Comment by ikusteu** [comment]
The nav bar should feature a space to host #489 as I imagine it will be controlled by some global state (currently we use Redux for Snackbar) and that (container) element should render, I guess only one notification and be in charge of removing the notification in favor of new one (or after certain timeout)

**Comment by delasous** [comment]
Ok, suggest that we create 4 separate tickets whose objectives are:
1. In `package/ui` create a new `CustomerNav/TabItem.tsx` which adds new styles, and conforms to existing `LinkTab` props (in existing `CustomerNavigation` file).
2. In `package/ui` create a new `CustomerNav/Tabs.tsx` which:
  a. Renders a list of TabItems
  b. Uses mock styles (background, and deskop/mobile flex)
3. In `package/ui` create a new `TopBar` and `EisbukAvatar` which:
  a. Uses new styles
  b. Uses existing `EisbukAvatar` as a base, and replaces colour scheme to use Tailwinds palette
4. In `package/client/pages`, update `CustomerNavigation` which:
  a. Uses existing `CustomerNavigation` as base
  b. Uses new components above
  c. Removes "BookOffIce" as a Tab
  d. Adds a space (and timeout clear logic) for #489

**Comment by delasous** [comment]
Closing as all notes & tasks have been moved to more concrete tickets
