### ISSUE TITLE
Feature: NotificationToast: 1 pt

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#489]
#### Description: 
A component used instead of existing snackbar to show notifications such as: successfully booked, customer deleted, etc...

#### Mockup:
[![Screenshot from 2022-06-07 12-56-13](https://user-images.githubusercontent.com/396425/172363232-04aa2c78-0bcf-46c6-9ab8-e85c49a44c57.png)](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1520%3A27578)

#### Props (should extend `React.HTMLAttributes<HTMLElement>`):
- **variant** (required: string enum):
  - Success
  - Error
  - *possibly add neutral, but only if needed somewhere*
- **message** (required: string): 
  - should be HTML string and set using [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)
  - ☝️ this should enable parsing of html tags like: `This is <strong>Bold</strong>` -> This is <strong>Bold</strong>
  - we should just take care that messages aren't read from dynamic sources (to prevent XSS), but I really doubt that'll be the case
- **onClose** (optional: Function):
  - should get called on close button click

#### Storybook:
- Variants - success/failure
- WithHTML - should show some message including html tags passed in and processed (e.g. `<strong>`)

#### Functionality:
- onClose:
  - should display `x` button and call `onClose` function when clicked
  - no need to close by itself (should managed by some other state)
  - if we really need the self closing functionality ☝️ we can easily add that later

#### Possible enhancements:
- null

**Comment by delasous** [comment]
Spec looks good! My only query is around use of `dangerouslySet`. My approach would have been [this](https://codesandbox.io/s/beautiful-firefly-tnkjdb?file=/src/App.js) (what would you call this? A 'named slot'?), which allows both string and fragment that includes string + inline tags. Are there are disadvantages to this approach that outweigh the security disadvantage of `dangerouslySet`?

**Comment by ikusteu** [comment]
Well…this is passing a jsx fragment, which is of type JSX.Element (an object), I prefer the string because it’s lighter to pass around and i18n is easier to implement when dealing with strings. Additionally, if you took React.Fragment (abbreviated ‘<>’ tags) and did dangerouslySetInnerHtml, it would produce the same result

**Comment by ikusteu** [comment]
It’s dangerous only if you insert a string received from an unreliable source (e.g. Form input), but we will have predefined strings

**Comment by delasous** [comment]
Ok, happy to stick with `dangerouslySet`!
