### ISSUE TITLE
Feature: EmptySpace: 1 pt

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#490]
#### Description: 
A "toast" element holding a message that no items are available. To be used to render messages like "no slots available" and "booking is locked for this month" (in case of countdown). This component is purely presentational

#### Mockup:
[![Image](https://user-images.githubusercontent.com/396425/172362922-6290ce2b-5a7c-467b-b23c-8c4b786c1de4.png)](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1514%3A37124)

#### Elements:
- a static icon (exclamation mark)
- a message text, received through props

#### Props:
- **message** (required: string)

#### Storybook:
- Default

#### Functionality:
- null

#### Possible Enhancements:
- null

**Comment by delasous** [comment]
LGTM
