### ISSUE TITLE
Feature: IntervalCard: 5 pts

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#495]
#### Description:
A card used to render a card for a slot interval. Existing `BookingCard` could be used as reference (as this is a styled rewrite of the same component)

#### Mockup:
[![Screenshot from 2022-06-08 11-33-10](https://user-images.githubusercontent.com/396425/172584042-7c492bf1-aa32-424a-9daf-1c6d67e03db0.png)](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1511%3A29065)

#### Props:
- **type** (required: SlotType):
  - ice
  - off-ice
- **date** (required: ISO date string):
  - e.g. "2022-01-01"
- **notes** (optional: string):
  - slot notes
  - will be the same for all intervals belonging to a particular slot
- **state** (optional: string enum):
  - default (default)
  - active (`booked` in `BookingCard`)
  - faded
  - disabled 
- **variant** (optional: string enum):
  - Booking (default):
    - used for customer bookings view
  - Calendar:
    - used for calendar view
  - Simple:
    - used for confirmation dialog
- **onBook** (optional: Function):
  - if not provided should provide an empty function as fallback
  - `() => void` (parameters can be provided when rendering the `IntervalCard`, no need to pass anything from inside the component)
- **onCancel** (optional: Function):
  - if not provided should provide an empty function as fallback
  - `() => void` (parameters can be provided when rendering the `IntervalCard`, no need to pass anything from inside the component)

#### Elements:
- date string
- time string (start time - end time)
- notes
- type icon:
  - components: #498 
- button:
  - components: #486 

#### Styles:
- [Booking](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1511%3A29065) variant:
  - doesn't show the date string
  - `default`:
    - shows default colour scheme (first on the mock)
    - shows `Book <duration>` button (of appropriate colour for type)
  - `active`:
    - shows outline of appropriate colour (with respect to **type**)
    - shows "cancel" button
  - `faded`:
    - shows faded colour scheme (second variant on both mockups)
    - shows `Book <duration>` button (of appropriate colour for type)
  - `disabled`:
    - shows disabled colour scheme
    - shows a full grey colour scheme
    - shows disabled `Book <duration>` button
    
- [Calendar](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1502%3A25675) variant:
  - shows all elements
  - regardless of **state** should always be rendered as `active` ☝️

- [Simple](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1514%3A36896) variant:
  - shows only date string and time string elements
  - regardless of **state** should always be rendered as `active` ☝️ (with a limited subset of elements)

#### Storybook:
- Variants:
  - should show all three variants for the same slot (Booking should be **state** = "default")
- BookingStates:
  - should show all **state**s for **type** ice
  - should show all **state**s for **type** off-ice

#### Functionality:
- should pass all of the tests for `BookingCard`

#### Enhancements:
- create `IntervalCardGroup` -> more/less the same as `BookingCardGroup`, only using newly created `IntervalCard`

#### Depends on:
- [x] #498 
- [ ] #486 

#### TODO:
- create style variants:
- create stories:
- pass the tests (update the tests if needed):
- create `IntervalCardGroup`

**Comment by delasous** [comment]
New `IntervalCard` component also needs to borrow logic from `BookingCard/Duration.tsx` to "Calculate Interval Duration" from the `timeString` prop. 
As described by @ikusteu [here](https://github.com/eisbuk/EisBuk/issues/484#issuecomment-1141262497), the returned duration should be used as a key to access an array-value of pre-calculated tailwind classes that will determine the size of the card. 
Duration should also be passed to #497 to display duration length on a badge that will be added as `endAdornment` to #486

**Comment by delasous** [comment]
Add Enhancement: Create new `SlotsDayContainer.tsx` that is equivalent to existing component, but which uses new `IntervalCardGroup`, and removes MUI components & styles in  lieu of our own tailwind styles
