### ISSUE TITLE
Feature: DurationBadge

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#497]
## Component: DurationBadge
A badge that highlights the duration of the interval that is about to be booked. Will be passed as `endAdornment` of #486, and composed in #495.
This component will not be used globally, and should be written as a local component, next to IntervalCard in `packages/ui/IntervalCard/DurationBadge.tsx`

**Mockup: [Figma](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1514%3A35158)**

### Requirements:
**Props**
- duration (required: BookingDuration enum)
- colour (required: string enum)
  - ice
  - off-ice

**Storybook**
- Colour variants: ice / off-ice

### Discussion:

- [ ] How many durations should there be, i.e. how would the edge cases be handled:
  - my idea is that if something is less than an hour, it would be `0.5h` and if something is more than 2h it would be `2+` as a catch all/failsafe (so that the app doesn't break if weird interval duration is input by mistake)
  - so my question here is: should `1h` and `2h` be a catch all for their respective edge cases, or should we introduce `0.5` and `2+` (I'm hoping @silviot can chime here....more like make a decision)
  - should we maybe add this check in `SlotForm` so that intervals longer than 2hours and less than 1hour (45mins or whatever is considered an hour) cannot be saved. This very restrictive, but in case a client actually needs it, they can contact us and we can make improvements, rather than falling back to some weird catch-alls

- [ ] How should we label the `1.5h` duration:
  - `11/2h`
  - `1h 30mins` (I, @ikusteu, prefer this)

**Comment by ikusteu** [comment]
I don't think this needs to be a separate ticket, but rather a task on #495. The unit of work will actually only include colour and duration display. Both of those things can be simple objects
```typescript
durationColourClass = {
  [SlotType.Ice]: "bg-<some-colour>",
  [SlotType.OffIce]: "bg-<some-colour>"
}

const durationLabel = {
  [Duration["1h"]]: "1h",
  [Duration["1.5h"]]: "1h 30min",
  [Duration["2h"]]: "2h",
}
```

**Comment by ikusteu** [comment]
We need to implement the logic to calculate duration in #495 anyhow, so this could just live there as well.

**Comment by ikusteu** [comment]
I would like to use this issue to discuss some points regarding duration calculation and preferred way of showing 1.5h duration.

**Comment by delasous** [comment]
We have agreed on "1.5h" duration as format.
Max limit is 2 hours (TODO: We need to limit this on Admin forms).

Closing as work is covered in #495
