### ISSUE TITLE
Feature: MainNav

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#499]
# Component: MainNav
**Description**:
A general purpose top-level nav bar for app routing. Will currently be used to display "Book" and "Calendar" routes in CustomerNav (link) of Athlete/Customer Area, but could also be leveraged when Admin area is revamped.

**Mockups:**
- [Bar](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1505%3A26339)
- [TabItem - Desktop](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1503%3A27899) 
- [TabItem - Mobile](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1505%3A26404)

**Tasks:**:
- [ ] In `package/ui` create new components:
  - [ ] `MainNav/TabItem`
  - [ ] `MainNav/NavBar`

**Requirements:**
1. `TabItem`
  a. Styles: To spec of "Tab Item Desktop | Mobile" mocks above - (Icon slot on left, and flex-col wrap on small screen)
  b. Props:
    - `href/to` - (required) string pathname
    - `label` - (required) string link display name
    - `Icon` - (optional) JSX.element - SVG Icon to render for the button link  
    
2. `NavBar`
  a. Styles: To spec of "Bar" mock above (background, and deskop/mobile flex)
  b. Props:
    - Links (required) array of:
      - href
      - label
      - Icon

3. Storybook - Default

**Comment by delasous** [comment]
Open to suggestions for better name, "MainNav" is WIP - feel free to edit ticket directly

**Comment by ikusteu** [comment]
Closing this as #500 and respective sub-components address all of the functionality described above

**Comment by ikusteu** [comment]
Closing this as https://github.com/eisbuk/EisBuk/issues/500 and respective sub-components address all of the functionality described above
