### ISSUE TITLE
Use an arbitrary time period when an athlete trains for a time different than booking

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#509]
Currently when an athlete shows up (is not absent) but trains for a period different than booked, we only let admins choose a different (existing) interval from the same slot.

Ideally the admins should be able to specify any duration, even if there is no corresponding interval.

This requires a change to the data model and a migration.

**Comment by ikusteu** [comment]
> This requires a change to the data model and a migration.
Plus the UI

**Comment by silviot** [comment]
This can be also tackled this way:

* currently admins might not be able to log arbitrary durations because there's no interval in the slot with the duration they'd like
* admins can still go to the slot edit page, and add a time interval of the duration they'd like. This would not affect booking, since that ship's sailed already, for a slot in the past
* we could make this simple by adding a piece of UI in the attendance page that would create a new time interval with the desired duration
