### ISSUE TITLE
Feature: UserAvatar Menu Enhancement

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#526]
Below the UserAvatar mock there is an additional [DropDown Menu](https://www.figma.com/file/oAzgMQW7vCaZAYmL58lxeo/Eisbuk?node-id=1514%3A34016) component which (I assume) should expand from the Avatar onClick to present the user with links/actions related to their account. As far as I am aware, there is currently no need for athlete user "Settings" right now (although there may have been talk about letting them edit their own name, email etc?), but there is an immediate need to provide them with the option to "Logout" - @silviot @ikusteu?

Just raising this ticket as a discussion point for now. If it's agreed that this functionality is desirable, I will elaborate on an enhancement to UserAvatar that will enable a dropdown menu if a links array is passed.

**Comment by ikusteu** [comment]
Yeah…thanks for bringing this up, I totally forgot about it. I wouldn’t include it in the ticket (as I imagine you didn’t). 
I don’t know about customer preferences, but we should also discuss admin “menu” (the one that used to expand from the logo, including logout). Let’t talk about this in the meeting (in the future I guess, as today’s should be really timeboxed)

**Comment by delasous** [comment]
Closing as this enhancement will only be required when we get to Admin re-haul. "Logout" functionality is currently not required for Athlete users.
