### ISSUE TITLE
Feature: Text Input

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#590]
Component: Text Input

**Description:**
A basic input field which allows users to enter text, and displays an error when input validation fails. This is a presentational component - input/form state will be handled with Formik and passed to the component via the FormikField props.

Part of #504.

**Mockup**:
1. [Input State Variants](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2012%3A29714)
2. [Prototype with Label, Error Text and Display](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2012%3A30142)

### Requirements:
**Props:**
1. label - required: string
2. formikField - required: Formik.FieldProps (consists of Input, Meta and Form props)
3. disabled - boolean = false;
4. placeholder - optional: string
5. startAdnorment - optional: JSX.Element

**Implementation:**
1. The formikField context provides `.touched` and `.error` state to the component [see their docs ](https://formik.org/docs/api/field): this should be used to conditionally render the error message.
2. Disabled should be used to toggle Edit vs Display state. Whole form edit/display will be toggled at once so elements are switched in place.

**Styles:**
1. Error message text should be considered in elements box, i.e should not cause Input to be offset when its present.

**Storybook**
1 . Prototype state variants with startAdornment:
  a. Default with placeholder
  b. Error
  c. Display (Filled)
  d. Display (Empty)

**Functionality**
Null

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
> Styles:
Error message text should be considered in elements box, i.e should not cause Input to be offset when its present.

Yes...Thank you! So many (large companies') pages do this wrong.

**Comment by ikusteu** [comment]
I would take [this](https://github.com/librocco/librocco/issues/63) into account, along with the mockup (in Librocco's Figma). It might be an overkill, but then again it might not be...we would, at some point need input adornment, prefix, suffix, meta, etc...Furthermore, if we develop it here, we can simply reuse it in Librocco (as well as all form elements)
