### ISSUE TITLE
Feature: Customer Form

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#592]
## Component: Customer Form

**Description:** 
A full-screen/responsive re-write of `client/src/components/CustomerForm` which uses #590, #591, #593 and new UI pkg `Button`. Component should use Formik to manage form state and wrap Input/Checkbox's in Formik's `Field` component. Whole form can be toggled between Edit/Display with form Fields changing in place.

Part of #504 

**Mockup**:
1. [Desktop - Display](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2012%3A29199)
2. [Mobile - Display](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2026%3A32844)
3. [Desktop - Edit](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2012%3A28718)
4. [Mobile - Edit](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2026%3A32847)

### Requirements:
**Props:**
1. customer - required: Partial of Customer (minus "subscriptionNumber")
2. onCancel - optional: callback to be fired onClick of "Cancel" button when in Edit mode = `() => {}`
3. onSave - optional: callback to be fired onClick of "Save" button when in Edit mode = `() => {}`

**Implementation:**
1.  Define local button “prototypes” ⇒ [Mock](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=1520%3A27766)
    1. Secondary Cyan + Pencil, with small screen icon only = “Edit”
    4. Positive Green + Check = “Save”
    5. Neutral = “Cancel” / “Go Back”
2. Create a Formik `Field` wrapper which can accept and control TextInput, DateInput or Checkbox state: Default, Error, Disabled...
3. Defines local "mode" state variable which is set when clicking Edit, Cancel or Save to toggle all form fields between Edit or Display mode
4. Uses existing Yup "Customer Validation" 

**Styles:**

**Storybook**
Default which can toggle back and forth between Edit and Display

**Functionality**

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
> onCancel - optional: callback to be fired onClick of "Cancel" button when in Edit mode = () => {}

I don't think this is necessary as the changes will be stored in local state, where cancel will only switch between edit and display-only mode.
