### ISSUE TITLE
Feature: Badge

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#612]
## Component: Badge

**Description:** Somewhat reflecting MUI's `Badge` component, should wrap its children in a `relative` container and add a (rounded) badge element positioned `absolutely` with respect to the container. We should also enable additional props to add content to the badge (such as text/icon), position the badge, etc.

#### Elements:

- Container:
  - a div element wrapping the children in a relative container
- Children:
  - should be rendered inside the container
- Badge:
  - should be rounded and (absolutely) positioned in the corner (top left, top right, bottom left, bottom right) of the container.

#### Styles:

- one suggestion is to use the padding instead of the width/height for the badge - that way an empty badge can have one size and badge with content can expand in size to be able to appropriately house the content
- if `badgeContent` string (one to two letters), we can add a wrapper with explicit width/height to keep the round shape

#### Props:

- **position** (optional: string enum):

  - top-left (default)
  - top-right
  - bottom-left
  - bottom-right

- **hidden** (optional: boolean):

  - used to conditionally render the badge

- **badgeContent** (optional: string | JSX.Element):

  - used to render some content inside the badge

- **colorClass** (optional: string):

  - should be a Tailwind color class
  - we should provide some default fallback in case of absence

#### Storybook (stories):

We can use UserAvatar as content to render the badge on top of

- Positions:
  - all position variants
- WithContent:
  - string
  - icon

**Comment by ikusteu** [comment]
@delasous I see you've mentioned this is #646, but it seems to be solved with the specific badge component for variance table (AttendanceVarianceBadge)...If this ticket is no longer needed, I would close it and use badges specific to each use case. Let me know if that's the case.

**Comment by delasous** [comment]
Yeah close it. Agree with component specific badge implementations
