### ISSUE TITLE
Feature: Text Area

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#613]
Component: Textarea

**Description:**
A basic text area input field which allows users to enter text. 
Comes with an optional Label, Help Text, Placeholder.
An additional Actions Panel is defined to provide:
1. Supporting functionality - e.g Additional Help via "?", attachments, emoji keyboard...
2. Main "Confirm" | "Cancel" functionality to explicitly toggle edit / display of the text area content.
This is a presentational component - input state will be handled with Formik and passed to the component via the FormikField props.

Related to #505 

**Mocks:** [Textarea](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2116%3A28902)

## Requirements
**Props should extend React.HTMLAttributes<HTMLTextAreaElement>:**
1. formikField - required: Formik.FieldProps (consists of Input, Meta and Form props)
3. label - optional: string
4. helpText - optional: string;
5. placeholder - optional: string
6. disabled - boolean = false;
7. showActions - boolean = false;
8. actions - optional: object: 
    1. supporting: array `{ Icon, onClick }[]`
    2. main: object 
        1. onConfirm: optional: callback function for _save_ main action
        2. onCancel: optional callback function for _cancel_ main action 

**Implementation**
1. The "disabled" state of the component represents its edit/display presentation. 
2. Actions panel should only be rendered if showActions = true & disabled != true
3. The onConfirm & onCancel "main action" icons should only be shown if respective handlers are passed via props. They can be used to explicitly toggle the disabled / display state of the field, as well as trigger side effects. Their action should only be enabled if there is change in the inputs value.
4. The "?" icon on the left of the mock is an example a "supporting action". If passed, the array of icons should be rendered in a container here.

**Styles**
1. Hover & Focus styles are detailed in [Textarea input](https://www.figma.com/file/3ndhFlpGT36awa7RyOR5yK/Eisbuk-(EDIT)?node-id=2042%3A28679) mock
2. CSS `resize: vertical` should be applied to textarea.

**Stories**
1.  Default - with label & helpText
3. w/ Actions Panel - showing main actions icons (cross & tick)
4. Display

**Comment by ikusteu** [comment]
This looks good, but I'd rather just have a plain textarea and then create a different component (wrapping this one) for more advanced use cases (like the interval card notes) handling action buttons and all.
The wrapper might and might not come with its own `Formik` instance, etc...
