### ISSUE TITLE
Attendance interval arrows work the opposite way

### ISSUE THREAD

**Issue by fadwamahmoud** [eisbuk/EisBuk#665]
Left arrow increases and right one decreases on both chrome and firefox

**Comment by ikusteu** [comment]
I'm not quite certain that's the case...the logic for interval arrows is such:
- of two intervals, longer one takes precedence (it's placed before the shorter interval)
- if two intervals are of same length, the one starting before takes precedence 

I get the behaviour described above, so I don't think it's a bug, @silviot could you chime in here, as I remember there being some confusion about the right ordering - this seems to be the same logic as for displaying of the intervals in customer area, and if I remember correctly, the logic on attendance page should have been different (or we've changed the requirements in the mean time...I don't remember anymore haha)

**Comment by ikusteu** [comment]
@fadwamahmoud is this still the case?
