### ISSUE TITLE
Customer form does not save edits

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#668]
Clicking the `Save` button on the form does nothing.

**Comment by ikusteu** [comment]
I’ve tried it just now and what I see happening is that the customer does get saved, only the customer modal doesn’t get updated with the newest props (if you close and then open a modal it’s updated and that’s something I already have in my backlog)

**Comment by silviot** [comment]
Correct, it is working. I don't know what I saw. Sorry for the noise.
