### ISSUE TITLE
SecretKey is removed from local storage on Booking view unmount 

### ISSUE THREAD

**Issue by fadwamahmoud** [eisbuk/EisBuk#676]
Steps to reproduce:
1. Book a slot => will get booked 
2. Click on profile tab
3. Go back to book tab
4. Try to book a slot => won't get booked

**Comment by ikusteu** [comment]
Not a bug as much as a necessary update. It is intentionally removed on unmount (useEffect), but that approach is no longer valid (and had some shortcomings before, like not being able to view two different customer area pages in two different tabs as it uses local storage).

My idea was to move it to redux, but that would produce a lot of complexity in test setups, so this kinda depends on #583 which I’ve already worked substantially and will be ready to merge after next week (as I imagine next week being librocco).

Anyhow, let’s leave this open as a reminder, but let’s wait for redux factory updates before tackling this.

**Comment by fadwamahmoud** [comment]
Yeah, but the buggy behaviour I'm referring to is that it's removed when you leave and then get back to the `Book` tab so you can't perform any booking actions. That's because `useSecretKey` being used inside the Profile view in addition to the customerArea page (so it's removed on the unmount of Profile view).
Turns out it's an easy fix. I removed the hook and used useParams instead to get the secretKey and now it's fixed. @ikusteu
