### ISSUE TITLE
Email Templates UI

### ISSUE THREAD

**Issue by fadwamahmoud** [eisbuk/EisBuk#716]
I'm creating this issue to lay down what's needed for this task so that we could have a more detailed discussion.

When admins need to edit a template (or create a new one, but that's for a later issue), they'd go to their organization settings then the template settings tab. Each template will be rendered in a tabNav like the github one.
For each template editing tab there are two fields; one for the subject and one for the html.
On top of each field there are buttons for each of the field names, rendered from a hardcoded list. The button label is the a human readable translated `fieldName`, when clicked it adds the fieldName of said field to the position where the cursor is. The admin can add however many instances of the same field they want. A live preview field  displays the template with the fieldNames replaced with their equivalent dummy values. 

### Components:

1.  OrganizationSettings tabNav

A new panel needs to be created for the templates page 

2. EmailTemplate

Contains a tabNav (like the github one) one tab for editing and the other for preview.
Each tab panel contains two fields for subject and html.
On the editing panel, clicking on a FieldName button inserts the FieldName's value into the editing field like so {{ fieldName }} into the position of the cursor. Clicking on the preview panel triggers the interpolate function which displays the template with the dummy values.

Editing field:
`Ciao, {{ name }}`

Preview field: 
`Ciao, Saul`

Removing any character from {{ name }} would just treat it as a regular string and it wouldn't be interpolated. Since the user knows how the template would look like, they would probably figure out they shouldn't mess with the FieldName. 

Editing field:
`Ciao, {{ name }`

Preview field: 
`Ciao, {{ name }`

4. Buttons

A group of Button components for each of the fieldValues for a specific email template

### Functionality

1. Insertion/Selection replacement:

When one of the FieldName buttons is clicked it inserts the fieldName value into the position of the cursor `selectionStart` or if it's a selection it replaces it. 

2. Preview
interpolation function is triggered and fieldValues are replaces with dummy values.

3. OnSubmit

Preview fields not submitted with the rest of the organizationData.

**Comment by ikusteu** [comment]
>(or create a new one, but that's for a later issue)

I don't think creating of the new templates is in our scope (as far as I'm informed) as that would be a huge amount of work.

**Comment by ikusteu** [comment]
The `+` `-` idea is interesting, but I don't think it's necessary...I would just let the button add the `{{ placeholder }}` to the text...I think people will be smart enough to delete it (as the editing will show the result immediately)

**Comment by ikusteu** [comment]
>Contains a tabNav (like the github one) one tab for editing and the other for preview.

I would really prefer to show the preview right below the input field as it's better UX IMO: I think you would need to explain much less (in terms of some usage help) and let the person try it and see the result immediately.

**Comment by ikusteu** [comment]
>Removing any character from {{ name }} would just treat it as a regular string and it wouldn't be interpolated.

I agree, I would just like to stress that `{{ name}}` or `{{name }}`, etc. should still work, but that shouldn't be the problem as the current `interpolateText` function (already in master) takes care of that.

**Comment by ikusteu** [comment]
>Current position of the cursor (when a button has been clicked) has to be kept in a local state to be returned to after the fieldValue has been inserted.

I would much rather not use state for this, but a ref (to the textarea), as ref is mutable and doesn't trigger rerenders, while state does (and is completely unnecessary here). Here's my minimal example of how this should work:

```jsx
import React from "react";

export const Example = () => {
  // Keep a ref of the input element
  const input = React.useRef<HTMLInputElement>(null);

  const [value, setValue] = React.useState("");

  // Insert "foo" at the current cursor position (or replace the selection)
  const insertFoo = () => {
    if (input.current) {
      const [start, end] = [
        input.current.selectionStart,
        input.current.selectionEnd,
      ];

      if (start !== null && end !== null) {
        // Update the state of the controlled component ('value' -> controlling the value of our input element)
        setValue([value.slice(0, start), "foo", value.slice(end)].join(""));
      }
    }
  };

  return (
    <div>
      <input
        // Make the element controlled
        value={value}
        onChange={(e) => setValue(e.target.value)}
        // Set the ref of the input element
        ref={input}
      />
      <button onClick={insertFoo}>Insert Foo</button>
    </div>
  );
};

```

**Comment by ikusteu** [comment]
I agree with the two top level tabs (in admin preferences):
- general
- email templates

and a tab for each template. 

In connection to #704 I would prefer it if you used `FormSection` and `FormField` (maybe extend a `FormField` with `textarea` variant) to make your work easier, as well as to keep the style consistent throughout.

The only problem is that said components are not yet in master, but rather in #715 

As for the `+` `-` it really seems like overcomplicating to me, so I would omit it.

**Comment by silviot** [comment]
@fadwamahmoud Nice job laying this all out! I had some comments, but @ikusteu beat me to it: 

* creating new templates is not a needed functionality 
* I agree a `-` button is not strictly needed, and not having it simplifies the button component
* I agree that it would be better to show the preview without the need to change tab (as [described here](https://github.com/eisbuk/EisBuk/issues/716#issuecomment-1370290563)) but I think there should be a single set of placeholder-buttons at the top. I also think editable areas and preview should be grouped together.

This is how I think the components should be laid out (I tried to quickly sketch t in Figma but I only wasted 15 minutes):

| <samp><kbd>First name</kbd></samp> <samp><kbd>Last name</kbd></samp> <samp><kbd>Email address</kbd></samp> |
| ------------ |
| <b>Subject:</b> <samp>Important news for {{ first_name }} {{ last_name }}</samp> |
| <b>Email body</b>: <samp style="outline: 3px dotted red">Dear {{ first_name }}, we've heard you love latin, so we're sending some Latin nonsense your way. Here it is. Enjoy! Lorem ipsum {{ invalid {{ nonexisting }}dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </samp> |
| Preview |
| <b>Subject:</b> <samp>Important news for Saul Goodman</samp> |
| <b>Email body</b>: <samp style="outline: 3px dotted red">Dear Saul, we've heard you love latin, so we're sending some Latin nonsense your way. Here it is. Enjoy! Lorem ipsum {{ invalid dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </samp> |

**Comment by ikusteu** [comment]
>I agree that it would be better to show the preview without the need to change tab (as https://github.com/eisbuk/EisBuk/issues/716#issuecomment-1370290563) but I think there should be a single set of placeholder-buttons at the top. I also think editable areas and preview should be grouped together.

In this case, I would update my minimal example to include one ref (not initalised) and do `onFocus={(e) => inputRef.current = e.target}` for both elements. This way, we would keep track of the latest focused element, so when you click a button, the placeholder is applied to the correct input field (not both for instance).
