### ISSUE TITLE
Error when editing a self registered user

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#737]
When users self register the admin needs to edit their profile to fill in categories. I was not able to do it in production using the UI. I had to use the firebase console.

**Comment by ikusteu** [comment]
I've tried this locally, in staging (eisbuk.web.app) and production (igorice.web.app), but wasn't able to reproduce, @silviot could you try and reproduce it and provide the exact steps?

**Comment by silviot** [comment]
@ikusteu Try to edit this user: https://igoriceteam.web.app/athletes/88bRoQjk7aFMKeOr2PMT
