### ISSUE TITLE
Fix attendance view row click-ability

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#768]
Currently if the user clicks on a greyed arrow to change the slot (for instance, this happened to me when moving to the last available time period within a slot - I was "clicking until it turns grey") they're brought to the athlete profile page.
This is unexpected. The expected action is nothing.
See screenshot:
![image](https://github.com/eisbuk/EisBuk/assets/396425/4f3be8ca-0687-4fa8-a23d-5553551617f0)

**Comment by ikusteu** [comment]
Fixed in #767
