### ISSUE TITLE
Improve usability of athlete "approval": 5 pts

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#775]
When athletes self subscribe they need to be approved by an admin.

Unapproved athletes are shown in grey on the athlete page. It should be easier for an admin to answer the questions:
* how many athletes are there to approve?
* Are there any?
* How do I approve them?

I think a good way to improve on the current status could be:

* Display an icon at the top when there are athletes to approve
* A click on the icon should bring the user to a view (possibly at route `/athletes-to-approve`) where only athletes needing approval are shown.

**Comment by fadwamahmoud** [comment]
1. Create a new athletes_approval route
2. Add an icon + badge next to birthday icon that show number of athletes needing an approval (no badge if none)
3. AthleteApproval page is a CustomerGrid with a customers list of only the unapproved athletes (empty categories)

**Comment by ikusteu** [comment]
We don't need a new route. We can just have a toggle state on the `/athletes` page, with a query param `?approvals=true`
