### ISSUE TITLE
Sort categories in slot display

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#801]
Currently categories appear in what looks like a random order. They should be always in the same order. Alphabetical on the key works fine.
![image](https://github.com/eisbuk/EisBuk/assets/396425/f525e81e-a1b9-4fc0-9d5f-bca900ff5516)
---
On a sidenote, the slots above should have been a single slot with three time periods, since they have the same categorization.

**Comment by ikusteu** [comment]
> On a sidenote, the slots above should have been a single slot with three time periods, since they have the same categorization.

Should we implement some data trigger to aggregate slots with same categorisations then?

**Comment by silviot** [comment]
> Should we implement some data trigger to aggregate slots with same categorisations then?

God forbid! We'll educate admins about the difference. I think computers in general should do what they're told, and not second guess what you might have meant.
