### ISSUE TITLE
Bulk send email with booking link

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#898]
Trainers need a way to remind athletes to make their bookings once a month (most likely twice - five days before expiration and one day before).

Admins might have a screen to do the bulk sending, with a prepopulated template that they can edit.

**Comment by fadwamahmoud** [comment]
# Specs:

### Delivery Queue

1. Store emails in the same EmailQueue collection with each containing a new `timestamp` field, the athletes email and their booking link
2. use [pooled](https://nodemailer.com/smtp/pooled/) connections in nodemailer to pull the emails from the queue and send them
3. processDelivery as is

### Interface 

We already have a bookings link email template in the settings page, will add a dropdown + combobox for athletes names for the user to select which athletes to send the email to

**Comment by ikusteu** [comment]
I'm not sure if I got this, but I think you're missing the point. The delivery is good as is. 
The purpose of this ticket is to put multiple emails in the delivery queue (the rest, the delivery, is taken care of by the queue as is)

To this ticket should tackle:
- the view
- a function (probably a thunk) to go over all athletes and send them an email

All in all, I think the spec has more to do with the UX than the delivery

**Comment by ikusteu** [comment]
As for nodemailer's pooled connection. I think that's more applicable when using your own live backend. With firebase, we're using the cloud infrastructure, which will spin up as many containers as necessary for the lifetime of a cloud function.

Cloud functions run 1 function = 1 container and you can run as many functions at the same time (benefits of a cloud), but once those are done, the container is destroyed and there's no live backend, only firebase (and by extension cloud) API.

**Comment by fadwamahmoud** [comment]
- it should be super easy to send the standard mail to everybody. The standard mail should have placeholders for the deadline to submit bookings. The placeholder should probably also be in the subject (something like "book now - you have until 2023-12-28 to book your january lessons)

- it should be easy to change the text of the email, and restrict the athletes to send the email to.

- The general idea is that this will be used twice:
around the 20th of each month (after they defined the next month slots), to ask people to book their slots
around the 24th of each month, to send an email to the people who haven't yet booked (as seen on the athlete list)

- it's very useful to have the total hours booked by each athlete show up in the list
 
- the best widget to select atheltes is a widget that can contract and expand, when contracted, it only shows how many athletes will receive the email, when expanded, it shows a list of all athletes as checkboxes, the user can change the list of athletes acting on the checkboxes.
