### ISSUE TITLE
Add "Capacity" field to slots and create new "private lessons" category

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#899]
Sometimes they organize one to one private lessons slots. In this case a single person should be able to book, and after one person booked no one else should be able to.

To this end we can:
* create a new "private lessons" category
* add a "capacity" field to slots, that defaults to 0 (meaning no capacity limit)
* grey out slots that are already at capacity in the screen where athletes book their lessons

**Comment by ikusteu** [comment]
Fixed in #903

**Comment by ikusteu** [comment]
@silviot I've closed this as completed, but I now see:
> - grey out slots that are already at capacity in the screen where athletes book their lessons

I made it so that the fully booked slots aren't displayed to customers who haven't booked the slot (they're shown to those who have). Is that ok, or would you like the greyed out version?
